exports.seed = function(knex, Promise) {
  return Promise.all([
    knex('users').insert([
      {
        first_name: 'Elana',
        last_name: 'Kopelevich',
        username: 'elanalynn',
        email: 'ekopelevich@gmail.com',
        phone: '7204282792',
        location: '80220',
        tagline: 'Super duper cool.',
        bio: 'I am a web developer with a background in marketing and design. Outside of coding, I work on my design skills, speak at Meetups, and participate in mentoring programs.',
        avatar: 'https://pbs.twimg.com/profile_images/640659562349989888/AjokLNHY.jpg',
        is_banned: false,
        is_admin: true,
        created_at: '2015-02-01',
        updated_at: '2015-02-01',
      }, {
        first_name: 'Shad',
        last_name: 'Self',
        username: 'discypher',
        email: 'shadself@gmail.com',
        phone: '7203827717',
        location: '80220',
        tagline: 'super duper extremely awesome and cool',
        bio: 'I am a Web Developer with experience in a variety of development environments including *AMP, Java EE, and Ruby on Rails. Additionally, I have experience with Nginx, Node.js, and the latest in Web Development technologies such as HTML5, CSS3, CoffeeScript, Behavior Driven Development, and Test Driven Development. With a strong technical skill set in a variety of areas including web development, server administration, networking, and project management, I have proven to be successful in the multidisciplinary demands of Web Development.',
        avatar: 'https://lh3.googleusercontent.com/h6lCEROFNA4GqcTP05g08qRpRt2ni2BlEXkZsm7KfNjj-j81EpMyMoIvKtDoDZLHDvuCP3SpMQ=w1440-h900-rw-no',
        is_banned: false,
        is_admin: true,
        created_at: '2015-03-01',
        updated_at: '2015-03-01',
      }, {
        first_name: 'Bernie',
        last_name: 'Sanders',
        username: 'bdawg',
        email: 'bernie2020@gmail.com',
        phone: '1234567890',
        location: '11754',
        tagline: 'Shoulda been president.',
        bio: 'Bernard "Bernie" Sanders is an American politician who has been the junior United States Senator from Vermont since 2007. Sanders is the longest-serving independent in U.S. congressional history.',
        avatar: 'http://www.ontheissues.org/Bernie_Sanders.jpg',
        is_banned: false,
        is_admin: true,
        created_at: '2015-03-01',
        updated_at: '2015-03-01',
      }, {
        first_name: 'Annakin',
        last_name: 'Skywalker',
        username: 'kinsky',
        email: 'sw@gmail.com',
        phone: '9876443224',
        location: 'Boulder, CO',
        tagline: 'space nerd',
        bio: 'Discovered as a slave on Tatooine by Qui-Gon Jinn and Obi-Wan Kenobi, Anakin Skywalker had the potential to become one of the most powerful Jedi ever, and was believed by some to be the prophesied Chosen One who would bring balance to the Force. A hero of the Clone Wars, Anakin was caring and compassionate, but also had a fear of loss that would prove to be his downfall.',
        avatar: 'http://cdn.thedailybeast.com/content/dailybeast/articles/2015/12/29/how-anakin-skywalker-and-the-prequels-factor-into-star-wars-the-force-awakens/jcr:content/image.crop.800.500.jpg/48380421.cached.jpg',
        is_banned: false,
        is_admin: true,
        created_at: '2015-03-01',
        updated_at: '2015-03-01',
      },
    ]),
  ])
}
