exports.seed = function(knex, Promise) {
  return Promise.all([
    knex('stories').insert([
      {
        user_id: 1,
        parent_id: null,
        genre_id: 1,
        title: 'The Tale of the Lost Puppy',
        summary: 'A puppy get\'s lost. Oh no!',
        cover: 'http://cdn3-www.dogtime.com/assets/uploads/gallery/30-impossibly-cute-puppies/impossibly-cute-puppy-15.jpg',
        is_locked: false,
        lock_time: null,
        is_active: true,
        is_private: false,
        auto_approval: false,
        created_at: '2016-08-23',
        updated_at: '2016-08-24',
      },{
        user_id: 1,
        parent_id: 1,
        genre_id: 6,
        title: 'Galvanize and the Three Bears',
        summary: 'A group of full stack students move in with three bears',
        cover: 'https://s-media-cache-ak0.pinimg.com/236x/bf/4e/40/bf4e4067252227bd3f758bba7dcee2ff.jpg',
        is_locked: false,
        lock_time: null,
        is_active: true,
        is_private: false,
        auto_approval: true,
        created_at: '2016-08-23',
        updated_at: '2016-08-25',
      },{
        user_id: 3,
        parent_id: null,
        genre_id: 4,
        title: 'Galvanize and the Three Beers',
        summary: 'A group of full stack students fight to the death over three beers.',
        cover: 'https://i.ytimg.com/vi/4yikpWtIFU8/maxresdefault.jpg',
        is_locked: false,
        lock_time: null,
        is_active: true,
        is_private: false,
        auto_approval: false,
        created_at: '2016-08-23',
        updated_at: '2016-08-26',
      },
    ]),
  ])
}
